---
project_name: "movie-analyst"
env: "qa"
app_user: "movie_app_user"
# Must be an OS user that has the awscli credentials configured
# In AWS, is the default user for Ubuntu AMIs
awscli_user: "ubuntu"
aws_region: "us-east-1"

repo_url: "https://github.com/aljoveza/devops-rampup.git"
app_source_path: "/tmp/devops-rampup-master"
backend_name: "movie-api"
frontend_name: "movie-ui"

frontend_source_path: "{{ project_name }}-ui"
backend_source_path: "{{ project_name }}-api"

backend_dir: "/opt/{{ backend_name }}"
frontend_dir: "/opt/{{ frontend_name }}"
backend_port: 3000
frontend_port: 3030
# The IP must be completed or udpated after the EC2 backend instance deployment
backend_host: "192.168.17.173"
backend_url: "{{ backend_host }}:{{ backend_port }}"
# This URL has an ALB ID that changes every time the ALB is deleted and created again
frontend_url: "http://{{ project_name }}-alb-{{ env }}-1753415801.{{ aws_region}}.elb.amazonaws.com"

rds_identifier: "{{ project_name }}-mysql-{{ env }}"
db_name: "movie_db"
db_user: "{{ db_name }}_user"
aws_ssm_parameter_name: "/{{ project_name }}/{{ env }}/db_password"

