plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Env: qa

keyed_groups:
  - key: tags['Role']
    separator: ''
    prefix: ''

groups:
  app_servers: "tags['Role'] in ['frontend', 'backend']"

compose:
  ansible_host: private_ip_address

