---
project_name: "movie-analyst"
env: "qa"
app_user: "movie_app_user"
# Must be an OS user that has the awscli credentials configured
# In AWS, is the default user for Ubuntu AMIs
awscli_user: "ubuntu"
aws_region: "us-east-1"

repo_url: "https://github.com/aljoveza/devops-rampup.git"
app_source_path: "/tmp/devops-rampup-master"
backend_name: "movie-api"
frontend_name: "movie-ui"

frontend_source_path: "{{ project_name }}-ui"
backend_source_path: "{{ project_name }}-api"

backend_dir: "/opt/{{ backend_name }}"
frontend_dir: "/opt/{{ frontend_name }}"
backend_port: "{{ lookup('aws_ssm', '/' ~ project_name ~ '/' ~ env ~ '/backend/backend_port', region=aws_region) }}"
frontend_port: "{{ lookup('aws_ssm', '/' ~ project_name ~ '/' ~ env ~ '/frontend/frontend_port', region=aws_region) }}"
backend_url: "{{ lookup('aws_ssm', '/' ~ project_name ~ '/' ~ env ~ '/backend/backend_url', region=aws_region) }}"
frontend_url: "{{ lookup('aws_ssm', '/' ~ project_name ~ '/' ~ env ~ '/frontend/frontend_url', region=aws_region) }}"

rds_identifier: "{{ project_name }}-mysql-{{ env }}"
db_name: "movie_db"
db_user: "{{ db_name }}_user"
aws_ssm_parameter_name: "/{{ project_name }}/{{ env }}/db_password"

