- name: Configure Ansible node
  hosts: ansible
  connection: local
  become: yes
  tasks:
    - name: Install base pacakges
      apt:
        name:
          - python3
          - python3-pip
          - software-properties-common
        state: present
        update_cache: yes

    - name: Install Python libraries via pip3
      pip:
        name: 
          - boto3
          - botocore
        state: present
        executable: pip3

    - name: Install the google.cloud colection from Ansible Galaxy
      community.general.ansible_galaxy_install:
        type: collection
        name: google.cloud
