plugin: google.cloud.gcp_compute
projects:
  - courseproject-20201117
zones:
  - us-east1-b
filters:
  - labels.env = qa

keyed_groups:
  - key: tags['role']
    separator: ''
    prefix: ''

groups:
  app_servers: "tags['role'] in ['frontend', 'backend']"

compose:
  ansible_host: networkInterfaces[0].networkIP

